services:
  ai-job-hunter:
    build:
      context: .
      dockerfile: Dockerfile

    working_dir: /app

    volumes:
      - .:/app

    env_file:
      - .env

    environment:
      PYTHONPATH: /app

    command: python -m pytest -v